### ISSUE TITLE
not really an issue, just showing you something

### ISSUE THREAD

**Issue by basketofsoftkittens** [cutiepatootiebear/complex-logical-expressions#1]
https://github.com/cutiepatootiebear/complex-logical-expressions/blob/b8084a5f5e578815221e55d603332b951bbe74cf/scripts.js#L28

not really a bug, and im not sure what the requirements are. but a cool thing instead of doing string concatenation is doing es6 message template

```javascript
console.log(`I'd like two scoops of ${flavor} ice cream in a ${vessel} with ${toppings}`)
```

**Comment by cutiepatootiebear** [comment]
Roger. I have not heard of es6 message templating. Thanks for the helpful feedback.

**Comment by basketofsoftkittens** [comment]
salaaam. keep em coming! this is good stuff

**Comment by cutiepatootiebear** [comment]
https://imgur.com/gallery/qWtwBTQ

**Comment by cutiepatootiebear** [comment]
these are the reqs

 /*
 * Programming Quiz: Ice Cream (3-6)
 *
 * Write a single if statement that logs out the message:
 * 
 * "I'd like two scoops of __________ ice cream in a __________ with __________."
 * 
 * ...only if:
 *   - flavor is "vanilla" or "chocolate"
 *   - vessel is "cone" or "bowl"
 *   - toppings is "sprinkles" or "peanuts"
 *
 * We're only testing the if statement and your boolean operators. 
 * It's okay if the output string doesn't match exactly.
 */
